import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import PomodoroTimer from '../components/PomodoroTimer'
import { AppSettings } from '../types'

const Home: NextPage = () => {
  const [appSettings, setAppSettings] = useState<AppSettings>({
    timers: {
      workTime: 25,
      breakTime: 5,
      longBreakTime: 15
    }
  })
  const [workDone, setWorkDone] = useState<number>(3)


  return (
    <div>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-light-green w-full h-screen'>
        <Header workDone={workDone} />
        <PomodoroTimer appSettings={appSettings} setWorkDone={setWorkDone} workDone={workDone} />
      </main>

    </div>
  )
}

export default Home
